name: "IaC CI"

on:
  # run on pushes to main
  push:
    branches:
      - main
      - gh-readonly-queue/main/**
  # run on pull requests that target the main branch
  pull_request:
    branches:
      - main
  # run weekly on Monday at 12:00
  # schedule:
  #  - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  pulumi_preview_changes:
    name: 'Pulumi - Preview Changes'
    runs-on: ubuntu-latest

    # pull requests, pushes to branches other than the main branch, and scheduled runs
    if: github.event_name != 'push' || github.ref != format('refs/heads/{0}', github.event.repository.default_branch)

    concurrency:
      # on branches (when a push event happens), we want all builds to complete even if commits/merging happens faster to make it easier to discover at which point
      # something broke; else (on PRs and scheduled executions), we cancel "old" builds and run/(re)start the build with the latest changes
      group: ${{ github.event_name == 'push' && format('ci-main-{0}-{1}', github.workflow, github.sha) || format('ci-{0}-{1}', github.workflow, github.ref) }}
      cancel-in-progress: false

    env:
      PULUMI_STACK: ci

    defaults:
      run:
        shell: bash
        working-directory: '.'

    permissions:
      contents: read

    steps:
      - name: StepSecurity - Harden Github-hosted Runners
        uses: h0x0er/harden-runner@int # v2.8.0
        with:
          egress-policy: audit
          disable-telemetry: true
          disable-sudo: true
          agent-env: int-pull
          tls-env: agent

      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Node - Setup
        id: node_setup
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: NPM - Install Dependencies
        id: npm_install
        run: npm ci

      - name: GitHub - Generate App Token
        id: github_generate_app_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.PULUMI_APP_ID }}
          private_key: ${{ secrets.PULUMI_APP_PRIVATE_KEY }}

      - name: Pulumi - Preview Changes
        id: pulumi_preview_changes
        uses: pulumi/actions@18b5a33fc447ab919feb61f2bb41147a1b30ab40 # v5.2.4
        with:
          command: preview
          refresh: true
          cloud-url: file://./state
          stack-name: ${{ env.PULUMI_STACK }}
          secrets-provider: passphrase
          comment-on-pr: true
          edit-pr-comment: true
          message: 'Associated Git Commit: "${{ github.event.commits[0].message }}" by ${{ github.event.commits[0].author }} (sha: ${{ github.event.commits[0].id }})'
          github-token: ${{ steps.github_generate_app_token.outputs.token }}
          # on scheduled/cron-triggered runs, there shouldn't be any state change. if we have some state change, fail the build
          expect-no-changes: ${{ github.event_name == 'schedule' }}
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}

  pulumi_apply_changes:
    name: 'Pulumi - Apply Changes'
    runs-on: ubuntu-latest

    # only pushes to the main branch
    if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)

    concurrency:
      # only allow one concurrent job/workflow, since the workflow commits changes back to the git repo which could cause concurrency issues
      group: ${{ github.workflow }}
      # do not cancel builds, since we (potentially) update the state during the build
      cancel-in-progress: false

    env:
      PULUMI_STACK: ci

    defaults:
      run:
        shell: bash
        working-directory: '.'

    permissions:
      contents: read

    steps:
      - name: StepSecurity - Harden Github-hosted Runners
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit
          disable-telemetry: true
          disable-sudo: true

      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          # https://github.com/marketplace/actions/git-auto-commit#checkout-the-correct-branch
          ref: ${{ github.head_ref }}
          # this is the token that the "git-auto-commit" action is using, so we use the one from the app
          # https://github.com/marketplace/actions/git-auto-commit#commits-made-by-this-action-do-not-trigger-new-workflow-runs
          token: ${{ secrets.GH_AUTOMATION_TOKEN }}

      - name: Node - Setup
        id: node_setup
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: NPM - Install Dependencies
        id: npm_install
        run: npm ci

      # unfortunately, there isn't a more straight forward way of doing it, so we will utilize a workaround; see also:
      # https://github.com/pulumi/actions/issues/158
      - name: Pulumi - Check for Changes
        id: pulumi_check_changes
        uses: pulumi/actions@18b5a33fc447ab919feb61f2bb41147a1b30ab40 # v5.2.4
        continue-on-error: true
        with:
          command: preview
          refresh: true
          cloud-url: file://./state
          stack-name: ${{ env.PULUMI_STACK }}
          secrets-provider: passphrase
          # this config option fails the build step if there are changes, allowing to use the result to identify if we have changes
          expect-no-changes: true
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}

      - name: Pulumi - Report Status
        id: pulumi_report_status
        run: |
          # 'success' means in this context that we do not have any state changes
          # 'failure' on the other side means that we have at least one element that is changed within the state
          if [ '${{ steps.pulumi_check_changes.outcome }}' = 'success' ]; then
            echo "No state changes found. Nothing further to do. Stopping workflow here."
            echo "state_changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "State changes were detected. Going to apply the changes and persisting the updated state..."
            echo "state_changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Pulumi - Apply Changes
        id: pulumi_apply_changes
        uses: pulumi/actions@18b5a33fc447ab919feb61f2bb41147a1b30ab40 # v5.2.4
        if: steps.pulumi_report_status.outputs.state_changed == 'true'
        with:
          command: up
          refresh: true
          cloud-url: file://./state
          stack-name: ${{ env.PULUMI_STACK }}
          secrets-provider: passphrase
          message: 'Associated Git Commit: "${{ github.event.commits[0].message }}" by ${{ github.event.commits[0].author }} (sha: ${{ github.event.commits[0].id }})'
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}

      - name: GitHub - Setup GPG Keys
        id: github_setup_gpg
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4 # v6.1.0
        if: steps.pulumi_report_status.outputs.state_changed == 'true'
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Git - Commit and Push State Changes
        id: git_commit_push
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
        if: steps.pulumi_report_status.outputs.state_changed == 'true'
        with:
          commit_message: "chore: update state for the ${{ env.PULUMI_STACK }} stack [skip ci]"
          commit_options: --no-verify
          commit_user_name: ${{ steps.github_setup_gpg.outputs.name }}
          commit_user_email: ${{ steps.github_setup_gpg.outputs.email }}
          commit_author: pulumi-runner[bot] <${{ secrets.PULUMI_APP_ID }}+pulumi-runner[bot]@users.noreply.github.com>
          file_pattern: ./state/**
